application:
  port: 3000
database:
  driver: sqllite
  name: sql_db
  username: username
  password: password
whatsapp:
  dbdriver: sqlite3
  dbname: wa_db
  debug_level: DEBUG
view:
  default: "views/components/container/index.html"
log:
  level: 6