application:
  port: 3000
database:
  driver: sqllite
  name: panji_express.db
  username: username
  password: password
whatsapp:
  dbdriver: sqlite
  dbname: panji_wa.db
  debug_level: DEBUG
view:
  default: "views/components/container/index.html"
log:
  level: 6